// Builds the deployable site into dist/: the bundled page plus everything that
// turns a web page into something you can keep on a home screen — a manifest,
// a service worker, icons, and the meta tags iOS reads instead of the manifest.
//
// Every path it emits is relative, because GitHub Pages serves a project site
// from a subdirectory (/<repo>/) rather than from the origin root — absolute
// paths would resolve one level too high and 404.
//
//   node tools/site.js
//   node tools/site.js --base https://user.github.io/repo   # absolute og:image

import { mkdir, writeFile, readdir, copyFile, readFile, rm } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildBundle } from './bundle.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ASSETS = path.join(ROOT, 'src/assets');
const DIST = path.join(ROOT, 'dist');

const baseArg = process.argv.indexOf('--base');
const BASE = baseArg > -1 ? `${process.argv[baseArg + 1].replace(/\/+$/, '')}/` : '';

const NAME = 'A Sense of Scale';
const SHORT = 'Scale';
const DESC = 'Pinch and drag your way across 42 orders of magnitude — the Earth and the Moon, the solar system, '
  + 'light crawling outward at its real speed, and a ladder from a proton to the observable universe.';

const MANIFEST = {
  name: NAME,
  short_name: SHORT,
  description: DESC,
  start_url: '.',
  scope: './',
  display: 'standalone',
  display_override: ['standalone', 'minimal-ui'],
  orientation: 'any',
  background_color: '#04060d',
  theme_color: '#060a16',
  categories: ['education', 'science'],
  icons: [
    { src: './assets/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: './assets/icon-maskable-192.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
    { src: './assets/icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
    { src: './assets/icon-maskable.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'maskable' },
  ],
  // Long-press the home-screen icon and jump straight into one mode. The app
  // already boots from location.hash, so these need no extra code.
  shortcuts: [
    { name: 'Earth & Moon', url: './#earth-moon' },
    { name: 'Solar System', url: './#solar-system' },
    { name: 'Powers of Ten', url: './#powers-of-ten' },
  ],
};

const head = (version) => `
<meta name="description" content="${DESC}">
<meta name="theme-color" content="#060a16">
<meta name="color-scheme" content="dark">
<link rel="manifest" href="./manifest.webmanifest">
<link rel="icon" href="./assets/icon.svg" type="image/svg+xml">
<link rel="icon" href="./assets/favicon-32.png" sizes="32x32" type="image/png">
<link rel="apple-touch-icon" href="./assets/apple-touch-icon.png">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="${SHORT}">
<meta name="application-name" content="${SHORT}">
<meta property="og:type" content="website">
<meta property="og:title" content="${NAME}">
<meta property="og:description" content="${DESC}">
<meta property="og:image" content="${BASE}./assets/og.jpg">
<meta name="twitter:card" content="summary_large_image">
<!-- build ${version} -->
`.trim();

const REGISTER = `
<script>
  // Offline is the point once it lives on a home screen: launching from the
  // icon with no signal should still work.
  if ('serviceWorker' in navigator) {
    addEventListener('load', () => navigator.serviceWorker.register('./sw.js').catch(() => {}));
  }
</script>
`.trim();

const sw = (version) => `// Service worker — generated by tools/site.js, do not edit by hand.
const VERSION = '${version}';
const SHELL = 'shell-' + VERSION;
const FONTS = 'fonts-v1';

// Relative to the worker's own URL, so the same file works at the origin root
// and under a project path like /a-sense-of-scale/.
const SHELL_URLS = [
  './', './index.html', './manifest.webmanifest',
  './assets/icon.svg', './assets/icon-192.png', './assets/apple-touch-icon.png',
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(SHELL).then((c) => c.addAll(SHELL_URLS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== SHELL && k !== FONTS).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const { request } = e;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);

  // Google Fonts: serve what we have, refresh in the background.
  if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') {
    e.respondWith(caches.open(FONTS).then(async (cache) => {
      const hit = await cache.match(request);
      const live = fetch(request).then((res) => {
        if (res.ok || res.type === 'opaque') cache.put(request, res.clone());
        return res;
      }).catch(() => hit);
      return hit || live;
    }));
    return;
  }

  if (url.origin !== location.origin) return;

  // The page itself: newest wins, but never fail because the network did.
  if (request.mode === 'navigate') {
    e.respondWith(
      fetch(request)
        .then((res) => {
          const copy = res.clone();
          caches.open(SHELL).then((c) => c.put('./index.html', copy));
          return res;
        })
        .catch(() => caches.match('./index.html').then((r) => r || caches.match('./'))),
    );
    return;
  }

  e.respondWith(caches.match(request).then((hit) => hit || fetch(request).then((res) => {
    if (res.ok) {
      const copy = res.clone();
      caches.open(SHELL).then((c) => c.put(request, copy));
    }
    return res;
  })));
});
`;

// ---------------------------------------------------------------------------

const { html, moduleCount } = await buildBundle();

// The worker's cache name has to move whenever the page does, or an installed
// copy would keep serving the build it first saw.
const version = createHash('sha1').update(html).digest('hex').slice(0, 12);

const page = html
  .replace(/^(<title>.*<\/title>)/m, `$1\n${head(version)}`)
  .replace('</script>\n', '</script>\n');

if (!page.includes('rel="manifest"')) throw new Error('head injection failed — did the <title> line move?');

// Start clean: a file dropped from the build should not survive in the output.
await rm(DIST, { recursive: true, force: true });
await mkdir(path.join(DIST, 'assets'), { recursive: true });
await writeFile(path.join(DIST, 'index.html'), `${page}\n${REGISTER}\n`);
await writeFile(path.join(DIST, 'manifest.webmanifest'), `${JSON.stringify(MANIFEST, null, 2)}\n`);
await writeFile(path.join(DIST, 'sw.js'), sw(version));
// Keeps GitHub Pages from running the output through Jekyll.
await writeFile(path.join(DIST, '.nojekyll'), '');

for (const file of await readdir(ASSETS)) {
  await copyFile(path.join(ASSETS, file), path.join(DIST, 'assets', file));
}

let total = 0;
for (const dir of [DIST, path.join(DIST, 'assets')]) {
  for (const f of await readdir(dir, { withFileTypes: true })) {
    if (f.isFile()) total += (await readFile(path.join(dir, f.name))).length;
  }
}
console.log(`dist/ — build ${version}, ${moduleCount} modules, ${(total / 1024).toFixed(0)} KB total`);
